name: Deploy SAM Application

on:
  push:
    branches: [main]
    paths:
      - 'sam-comprehend/**'
      - '.github/workflows/sam-deploy.yml'
  pull_request:
    branches: [main]
    paths:
      - 'sam-comprehend/**'
      - '.github/workflows/sam-deploy.yml'
  workflow_dispatch:



#tror ikke Actions f√•r riktig stack-name
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Deploy SAM application
        working-directory: ./sam-comprehend
        run: |
          sam deploy --stack-name sam-comprehend-user49 \ 
            --s3-bucket user49-data \
            --region eu-west-1 \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides S3BucketName=user49-data \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
